<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Attendance Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 20px;
            margin: 0;
            color: #1e293b;
        }
        .header p {
            margin: 3px 0;
            color: #64748b;
            font-size: 11px;
        }
        .stats {
            display: flex;
            justify-content: space-around;
            margin-bottom: 20px;
            padding: 10px;
            background: #f8fafc;
            border-radius: 8px;
        }
        .stats .stat {
            text-align: center;
        }
        .stats .stat .number {
            font-size: 18px;
            font-weight: 800;
        }
        .stats .stat .label {
            font-size: 10px;
            color: #94a3b8;
        }
        .stats .stat .number.green { color: #16a34a; }
        .stats .stat .number.blue { color: #2563eb; }
        .stats .stat .number.red { color: #dc2626; }
        .stats .stat .number.orange { color: #d97706; }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th {
            background: #f1f5f9;
            padding: 8px 10px;
            text-align: left;
            font-size: 10px;
            text-transform: uppercase;
            font-weight: 800;
            color: #475569;
            border-bottom: 2px solid #e2e8f0;
        }
        td {
            padding: 8px 10px;
            border-bottom: 1px solid #e2e8f0;
            font-size: 11px;
        }
        .status-badge {
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 10px;
            font-weight: 700;
        }
        .status-badge.checkin { background: #dcfce7; color: #16a34a; }
        .status-badge.checkout { background: #dbeafe; color: #2563eb; }
        .status-badge.late { background: #fef3c7; color: #d97706; }
        .status-badge.absent { background: #fee2e2; color: #dc2626; }
        .footer {
            margin-top: 20px;
            padding-top: 10px;
            border-top: 1px solid #e2e8f0;
            font-size: 10px;
            color: #94a3b8;
            text-align: center;
        }
        .text-center { text-align: center; }
        .text-muted { color: #94a3b8; }
        .page-break { page-break-after: always; }
    </style>
</head>
<body>
    <div class="header">
        <h1>📋 Attendance Report</h1>
        <p><strong>Generated:</strong> {{ $generated_at }}</p>
        <p><strong>Generated By:</strong> {{ $generated_by }}</p>
        <p><strong>Total Records:</strong> {{ $total }}</p>
    </div>

    <div class="stats">
        <div class="stat">
            <div class="number green">{{ $totalCheckin }}</div>
            <div class="label">✅ Check-ins</div>
        </div>
        <div class="stat">
            <div class="number blue">{{ $totalCheckout }}</div>
            <div class="label">📤 Check-outs</div>
        </div>
        <div class="stat">
            <div class="number orange">{{ $totalLate }}</div>
            <div class="label">⏰ Late</div>
        </div>
        <div class="stat">
            <div class="number red">{{ $totalAbsent }}</div>
            <div class="label">❌ Absent</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Child</th>
                <th>Classroom</th>
                <th>Date</th>
                <th>Status</th>
                <th>Check-in</th>
                <th>Check-out</th>
                <th>Drop Off By</th>
                <th>Pickup By</th>
            </tr>
        </thead>
        <tbody>
            @forelse($attendances as $i => $attendance)
            @php
                $child = $attendance->child;
                $classroom = $child ? $child->classroom : null;
                $status = $attendance->status;
                $badgeClass = 'absent';
                $badgeText = 'Absent';
                
                if (in_array($status, ['checkin', 'present'])) {
                    $badgeClass = 'checkin';
                    $badgeText = 'Check-in';
                } elseif ($status == 'checkout') {
                    $badgeClass = 'checkout';
                    $badgeText = 'Check-out';
                } elseif ($status == 'late') {
                    $badgeClass = 'late';
                    $badgeText = 'Late';
                }
                
                $dropOff = $attendance->drop_off_by;
                if ($dropOff && is_numeric($dropOff)) {
                    $parent = \App\Models\ParentModel::find($dropOff);
                    if ($parent) {
                        $dropOff = $parent->name;
                    } else {
                        $user = \App\Models\User::find($dropOff);
                        if ($user) {
                            $dropOff = $user->name;
                        }
                    }
                }
                
                $pickup = $attendance->pickup_by;
                if ($pickup && is_numeric($pickup)) {
                    $parent = \App\Models\ParentModel::find($pickup);
                    if ($parent) {
                        $pickup = $parent->name;
                    } else {
                        $user = \App\Models\User::find($pickup);
                        if ($user) {
                            $pickup = $user->name;
                        }
                    }
                }
            @endphp
            <tr>
                <td>{{ $i + 1 }}</td>
                <td>{{ $child->name ?? 'Unknown' }}</td>
                <td>{{ $classroom ? $classroom->name : 'No Class' }}</td>
                <td>{{ \Carbon\Carbon::parse($attendance->date)->format('d M Y') }}</td>
                <td><span class="status-badge {{ $badgeClass }}">{{ $badgeText }}</span></td>
                <td>{{ $attendance->checkin_time ? \Carbon\Carbon::parse($attendance->checkin_time)->format('h:i A') : '-' }}</td>
                <td>{{ $attendance->checkout_time ? \Carbon\Carbon::parse($attendance->checkout_time)->format('h:i A') : '-' }}</td>
                <td>{{ $dropOff ?? '-' }}</td>
                <td>{{ $pickup ?? '-' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="9" class="text-center text-muted" style="padding:20px;">
                    No attendance records found
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>This report is auto-generated from KidsTrack System</p>
        <p>© {{ date('Y') }} KidsTrack - All Rights Reserved</p>
    </div>
</body>
</html>